# Generated by Django 3.2.6 on 2021-10-31 17:05

import os

from django.db import connection, migrations

# BASE_PATH = os.path.abspath(os.path.join(os.getcwd(), "..", "data_migration"))


# def load_data_from_sql(filepath):
#     file_path = os.path.join(BASE_PATH, filepath)
#     sql_statement = open(file_path).read()
#     return sql_statement


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        # migrations.RunSQL(load_data_from_sql("legacy_dbs/Antarctica.sql")),
        # migrations.RunSQL(load_data_from_sql("legacy_dbs/Alpine.sql")),
        # migrations.RunSQL(load_data_from_sql("legacy_dbs/Greenland.sql")),
        # migrations.RunSQL(load_data_from_sql("legacy_dbs/Tectonics.sql")),
        # migrations.RunSQL(load_data_from_sql("legacy_dbs/Calibration.sql")),
    ]
