# Generated by Django 3.2.6 on 2021-11-03 13:41
import os

from django.db import migrations

# BASE_PATH = os.path.abspath(os.path.join(os.getcwd(), "..", "data_migration"))


# def load_data_from_sql(filepath):
#     file_path = os.path.join(BASE_PATH, filepath)
#     sql_statement = open(file_path, encoding="utf8").read()
#     return sql_statement


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_base_data_load"),
    ]

    operations = [
        # migrations.RunSQL(load_data_from_sql("functions.sql")),
        # migrations.RunSQL(load_data_from_sql("copiers/Antarctica.sql")),
        # migrations.RunSQL(load_data_from_sql("copiers/Alpine.sql")),
        # migrations.RunSQL(load_data_from_sql("copiers/Greenland.sql")),
        # migrations.RunSQL(load_data_from_sql("copiers/Tectonics.sql")),
        # migrations.RunSQL(load_data_from_sql("copiers/Calibration.sql")),
        # migrations.RunSQL(load_data_from_sql("cleanup.sql")),
    ]
