# Generated by Django 3.2.6 on 2022-03-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220303_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='al_stds',
            options={'verbose_name_plural': 'Al Stds'},
        ),
        migrations.AlterModelOptions(
            name='be10al26quartz',
            options={'verbose_name': 'Be10 Al26 Quartz', 'verbose_name_plural': 'Be10 Al26 Quartz'},
        ),
        migrations.AlterModelOptions(
            name='be_stds',
            options={'verbose_name_plural': 'Be Stds'},
        ),
        migrations.AlterModelOptions(
            name='c14quartz',
            options={'verbose_name_plural': 'C14 Quartz'},
        ),
        migrations.AlterModelOptions(
            name='calibrationdata',
            options={'verbose_name_plural': 'Calibration Data'},
        ),
        migrations.AlterModelOptions(
            name='cl36',
            options={'verbose_name_plural': 'CL36'},
        ),
        migrations.AlterModelOptions(
            name='coresamplenuclidematch',
            options={'verbose_name_plural': 'Core Sample Nuclide Matches'},
        ),
        migrations.AlterModelOptions(
            name='he3pxol',
            options={'verbose_name_plural': 'He3 PXOL'},
        ),
        migrations.AlterModelOptions(
            name='he3quartz',
            options={'verbose_name_plural': 'He3 Quartz'},
        ),
        migrations.AlterModelOptions(
            name='imagefilescores',
            options={'verbose_name_plural': 'Image File Cores'},
        ),
        migrations.AlterModelOptions(
            name='ne21quartz',
            options={'verbose_name_plural': 'Ne21 Quartz'},
        ),
        migrations.AlterModelOptions(
            name='sampledocumentmatch',
            options={'verbose_name_plural': 'Sample Document Matches'},
        ),
        migrations.AlterModelOptions(
            name='samplepublicationsmatch',
            options={'verbose_name_plural': 'Sample Publication Matches'},
        ),
        migrations.AlterModelOptions(
            name='sampleuserdata',
            options={'verbose_name_plural': 'Sample User Data'},
        ),
        migrations.AlterModelOptions(
            name='userfieldsproperty',
            options={'verbose_name_plural': 'User Fields Properties'},
        ),
        migrations.AlterModelOptions(
            name='uthquartz',
            options={'verbose_name_plural': 'U Th Quartz'},
        ),
    ]
