# Generated by Django 3.2.6 on 2022-04-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220327_1541'),
        ('base', '0006_insert_triggers_further_cleanup'),
    ]

    operations = [
    ]
