# Generated by Django 3.2.6 on 2022-03-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220327_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalculatedAges',
            new_name='CalculatedAge',
        ),
        migrations.RenameField(
            model_name='calculatedage',
            old_name='sample_unique',
            new_name='sample',
        ),
    ]
