# Generated by Django 3.2.6 on 2022-03-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220327_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='be10al26quartz',
            name='_temp_sample_name',
        ),
        migrations.RemoveField(
            model_name='c14quartz',
            name='_temp_sample_name',
        ),
        migrations.RemoveField(
            model_name='cl36',
            name='_temp_sample_name',
        ),
        migrations.RemoveField(
            model_name='he3pxol',
            name='_temp_sample_name',
        ),
        migrations.RemoveField(
            model_name='he3quartz',
            name='_temp_sample_name',
        ),
        migrations.RemoveField(
            model_name='majorelement',
            name='_temp_sample_name',
        ),
        migrations.RemoveField(
            model_name='ne21quartz',
            name='_temp_sample_name',
        ),
        migrations.RemoveField(
            model_name='site',
            name='_temp_application_name',
        ),
        migrations.RemoveField(
            model_name='traceelement',
            name='_temp_sample_name',
        ),
        migrations.RemoveField(
            model_name='uthquartz',
            name='_temp_sample_name',
        ),
    ]
