# Generated by Django 3.2.6 on 2022-03-03 13:41

from django.db import migrations

trigger_sql = """
-- We need to create a trigger on each nuclide table to update the updated_at field of the associated sample
CREATE TRIGGER _be10_sample_delete_trigger
  AFTER DELETE ON _be10_al26_quartz
  FOR EACH ROW
    UPDATE base_sample
      SET updated_at = now()
      WHERE base_sample.id = OLD.sample_id;

CREATE TRIGGER _c14_sample_delete_trigger
  AFTER DELETE ON _c14_quartz
  FOR EACH ROW
    UPDATE base_sample
      SET updated_at = now()
      WHERE base_sample.id = OLD.sample_id;

CREATE TRIGGER _cl36_sample_delete_trigger
  AFTER DELETE ON _cl36
  FOR EACH ROW
    UPDATE base_sample
      SET updated_at = now()
      WHERE base_sample.id = OLD.sample_id;

CREATE TRIGGER _he3_pxol_sample_delete_trigger
  AFTER DELETE ON _he3_pxol
  FOR EACH ROW
    UPDATE base_sample
      SET updated_at = now()
      WHERE base_sample.id = OLD.sample_id;

CREATE TRIGGER _he3_quartz_sample_delete_trigger
  AFTER DELETE ON _he3_quartz
  FOR EACH ROW
    UPDATE base_sample
      SET updated_at = now()
      WHERE base_sample.id = OLD.sample_id;

CREATE TRIGGER _major_element_sample_delete_trigger
  AFTER DELETE ON _major_element
  FOR EACH ROW
    UPDATE base_sample
      SET updated_at = now()
      WHERE base_sample.id = OLD.sample_id;

CREATE TRIGGER _ne21_sample_delete_trigger
  AFTER DELETE ON _ne21_quartz
  FOR EACH ROW
    UPDATE base_sample
      SET updated_at = now()
      WHERE base_sample.id = OLD.sample_id;

CREATE TRIGGER _trace_element_sample_delete_trigger
  AFTER DELETE ON _trace_element
  FOR EACH ROW
    UPDATE base_sample
      SET updated_at = now()
      WHERE base_sample.id = OLD.sample_id;

CREATE TRIGGER _u_th_sample_delete_trigger
  AFTER DELETE ON _u_th_quartz
  FOR EACH ROW
    UPDATE base_sample
      SET updated_at = now()
      WHERE base_sample.id = OLD.sample_id;
"""


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0008_auto_20220327_1628'),
    ]

    operations = [
        migrations.RunSQL(trigger_sql)
    ]