# Generated by Django 3.2.6 on 2022-03-27 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_insert_triggers_further_cleanup'),
        ('base', '0009_auto_20220327_2203'),
    ]

    operations = [
    ]
