# Generated by Django 3.2.6 on 2022-04-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_merge_20220419_1340'),
        ('base', '0010_merge_20220327_2236'),
    ]

    operations = [
    ]
