# Generated by Django 3.2.6 on 2022-06-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_merge_20220419_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='link_color',
            field=models.CharField(default='#888888', max_length=8),
        ),
        migrations.AddField(
            model_name='application',
            name='visited_color',
            field=models.CharField(default='#666666', max_length=8),
        ),
        migrations.AddField(
            model_name='project',
            name='cores',
            field=models.ManyToManyField(related_name='cores', to='base.Core'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sites',
            field=models.ManyToManyField(related_name='applications', to='base.Site'),
        ),
    ]
