# Generated by Django 3.2.6 on 2022-06-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20220602_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='older_than',
            field=models.IntegerField(null=True),
        ),
    ]
