# Generated by Django 3.2.6 on 2023-02-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20221117_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='application',
        ),
    ]
