# Generated by Django 4.1.7 on 2023-03-31 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_publication_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='publications',
        ),
    ]
