# Generated by Django 4.1.7 on 2023-05-16 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_document_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='continent',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, to='base.continent'),
        ),
    ]
