version: "3.0"
services:
  database:
    image: mysql:8.0.13
    container_name: berkeley_iced_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: berkeley
      MYSQL_DATABASE: iced
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    command: --default-authentication-plugin=mysql_native_password

  application:
    build: .
    container_name: berkeley_iced_django
    ports:
        - "8000:8000"
    volumes: ['./django-app/:/var/www/berkeley-geo/app']
    working_dir: /var/www/berkeley-geo/app
    links:
      - database
    command: pipenv run python iced/manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_DEVELOPMENT: 1
    depends_on:
      - "database"
